/**
 * Clone-procedure tests for integrationsRouter.clone (PR 3/3).
 *
 * Coverage:
 *   1. Ownership — source belongs to caller → returns draft template
 *   2. Ownership — source belongs to a different user → NOT_FOUND
 *      (error message does not leak whether the row exists at all)
 *   3. Source doesn't exist → NOT_FOUND
 *   4. Name suffix: returned template name = "<source.name> (copy)"
 *   5. Excluded fields: NO id, userId, createdAt, deletedAt, pageId,
 *      pageName, formId, formName on the returned `template`
 *   6. Multi-destination: integration_routes order preserved in template.destinationIds
 *   7. Single-destination (no routes): destinationIds falls back to [destinationId]
 *   8. Per-routing variables (config.variableFields) carry over
 *
 * Why we don't unit-test the SQL-level ownership filter: the WHERE clause
 * is generated by `ownedBy(integrations, sourceId, userId)` from
 * server/lib/assertUserOwns.ts, which already has its own test coverage
 * (the critical-fixes sprint added it). Here we exercise the router-level
 * contract by mocking the DB chain.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../db", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../db")>();
  return {
    ...actual,
    getDb: vi.fn(),
  };
});

import { getDb } from "../db";
import type { DbClient } from "../db";
import { integrationsRouter } from "./integrationsRouter";
import type { TrpcContext } from "../_core/context";

interface SourceRowOverrides {
  id?: number;
  userId?: number;
  name?: string;
  facebookAccountId?: number | null;
  destinationId?: number | null;
  telegramChatId?: string | null;
  config?: Record<string, unknown>;
  pageId?: string | null;
  formId?: string | null;
}

function makeSourceRow(o: SourceRowOverrides = {}) {
  // Use `in` checks so explicit `null` / `undefined` overrides aren't
  // collapsed back to the default by `??`.
  const has = (k: keyof SourceRowOverrides) => Object.prototype.hasOwnProperty.call(o, k);
  return {
    id: has("id") ? o.id! : 42,
    userId: has("userId") ? o.userId! : 100,
    type: "LEAD_ROUTING" as const,
    name: has("name") ? o.name! : "shlang 64k/30k",
    config: has("config")
      ? o.config
      : {
          variableFields: { offer_id: "110566", stream: "abc" },
          targetWebsiteName: "100k.uz",
          targetTemplateType: "100k",
        },
    telegramChatId: has("telegramChatId") ? o.telegramChatId! : "-1001234567890",
    pageId: has("pageId") ? o.pageId! : "116110731485214",
    formId: has("formId") ? o.formId! : "1415829146966356",
    pageName: "Avval Bizda",
    formName: "Tibbiyot Forms - 4",
    destinationId: has("destinationId") ? o.destinationId! : 60016,
    facebookAccountId: has("facebookAccountId") ? o.facebookAccountId! : 5,
    isActive: true,
    createdAt: new Date("2026-05-09T14:26:46Z"),
    deletedAt: null,
  };
}

function makeMockDb(opts: {
  /** Rows returned by the first SELECT (source lookup); [] = not found / not owned */
  source?: ReturnType<typeof makeSourceRow>[];
  /** Rows returned by the integration_routes SELECT */
  routes?: Array<{ destinationId: number }>;
}): DbClient {
  const source = opts.source ?? [];
  const routes = opts.routes ?? [];
  let selectCount = 0;
  return {
    select: vi.fn(() => {
      selectCount++;
      const which = selectCount;
      return {
        from: vi.fn(() => ({
          where: vi.fn(() => ({
            limit: vi.fn(async () => source),
            orderBy: vi.fn(async () => routes),
          })),
        })),
      };
    }),
  } as unknown as DbClient;
}

function userCaller(userId = 100) {
  const ctx = {
    req: null,
    res: null,
    user: {
      id: userId,
      name: "Test User",
      email: "u@test.com",
      role: "user",
      password: null,
      facebookId: null,
      googleId: null,
      createdAt: new Date(),
    },
  } as unknown as TrpcContext;
  return integrationsRouter.createCaller(ctx);
}

beforeEach(() => vi.clearAllMocks());

describe("integrationsRouter.clone — ownership", () => {
  it("1. owned source → returns draft template", async () => {
    vi.mocked(getDb).mockResolvedValue(
      makeMockDb({ source: [makeSourceRow({ userId: 100 })], routes: [] }),
    );
    const result = await userCaller(100).clone({ sourceId: 42 });
    expect(result.clonedFrom).toBe(42);
    expect(result.clonedFromName).toBe("shlang 64k/30k");
    expect(result.template).toBeDefined();
  });

  it("2. source belongs to a different user → NOT_FOUND (mock returns empty per ownedBy filter)", async () => {
    // The router's WHERE clause is `ownedBy(integrations, 42, ctx.user.id) AND
    // isNull(deletedAt)` — when userId mismatches, the SQL returns no rows.
    // The mock simulates the empty result.
    vi.mocked(getDb).mockResolvedValue(makeMockDb({ source: [] }));
    await expect(userCaller(100).clone({ sourceId: 42 })).rejects.toMatchObject({
      code: "NOT_FOUND",
      message: expect.stringMatching(/not found/i),
    });
  });

  it("3. non-existent id → NOT_FOUND", async () => {
    vi.mocked(getDb).mockResolvedValue(makeMockDb({ source: [] }));
    await expect(userCaller(100).clone({ sourceId: 999999 })).rejects.toMatchObject({
      code: "NOT_FOUND",
    });
  });

  it("3b. NOT_FOUND message is generic (doesn't leak existence vs ownership)", async () => {
    vi.mocked(getDb).mockResolvedValue(makeMockDb({ source: [] }));
    const err = await userCaller(100).clone({ sourceId: 42 }).catch((e) => e);
    // Phrase shouldn't reveal whether the row exists at all (the "owned
    // by someone else" case must look identical to the "doesn't exist"
    // case).
    expect(err.message).not.toMatch(/another user|wrong owner|other tenant/i);
    expect(err.message).toBe("Integration not found or access denied");
  });
});

describe("integrationsRouter.clone — template shape", () => {
  it("4. name has ' (copy)' suffix", async () => {
    vi.mocked(getDb).mockResolvedValue(
      makeMockDb({ source: [makeSourceRow({ name: "shlang 64k/30k" })] }),
    );
    const result = await userCaller(100).clone({ sourceId: 42 });
    expect(result.template.name).toBe("shlang 64k/30k (copy)");
  });

  it("5. template excludes id, pageId, formId, pageName, formName, createdAt, deletedAt, userId", async () => {
    vi.mocked(getDb).mockResolvedValue(makeMockDb({ source: [makeSourceRow()] }));
    const result = await userCaller(100).clone({ sourceId: 42 });
    const t = result.template as Record<string, unknown>;
    expect(t.id).toBeUndefined();
    expect(t.userId).toBeUndefined();
    expect(t.pageId).toBeUndefined();
    expect(t.formId).toBeUndefined();
    expect(t.pageName).toBeUndefined();
    expect(t.formName).toBeUndefined();
    expect(t.createdAt).toBeUndefined();
    expect(t.deletedAt).toBeUndefined();
  });

  it("6. template includes type='LEAD_ROUTING' (matches the create mutation's schema)", async () => {
    vi.mocked(getDb).mockResolvedValue(makeMockDb({ source: [makeSourceRow()] }));
    const result = await userCaller(100).clone({ sourceId: 42 });
    expect(result.template.type).toBe("LEAD_ROUTING");
  });

  it("7. multi-destination: destinationIds preserves order from integration_routes", async () => {
    vi.mocked(getDb).mockResolvedValue(
      makeMockDb({
        source: [makeSourceRow({ destinationId: 60016 })],
        routes: [
          { destinationId: 60016 },
          { destinationId: 60020 },
          { destinationId: 60021 },
        ],
      }),
    );
    const result = await userCaller(100).clone({ sourceId: 42 });
    expect(result.template.destinationIds).toEqual([60016, 60020, 60021]);
  });

  it("8. single-destination (no routes): destinationIds falls back to [destinationId]", async () => {
    vi.mocked(getDb).mockResolvedValue(
      makeMockDb({
        source: [makeSourceRow({ destinationId: 60016 })],
        routes: [],
      }),
    );
    const result = await userCaller(100).clone({ sourceId: 42 });
    expect(result.template.destinationIds).toEqual([60016]);
  });

  it("9. no destinations at all → empty destinationIds array", async () => {
    vi.mocked(getDb).mockResolvedValue(
      makeMockDb({
        source: [makeSourceRow({ destinationId: null })],
        routes: [],
      }),
    );
    const result = await userCaller(100).clone({ sourceId: 42 });
    expect(result.template.destinationIds).toEqual([]);
    expect(result.template.destinationId).toBeNull();
  });

  it("10. per-routing variableFields carry over (offer_id, stream)", async () => {
    vi.mocked(getDb).mockResolvedValue(
      makeMockDb({
        source: [
          makeSourceRow({
            config: {
              variableFields: { offer_id: "110566", stream: "src-3" },
              targetWebsiteName: "100k.uz",
              targetTemplateType: "100k",
            },
          }),
        ],
      }),
    );
    const result = await userCaller(100).clone({ sourceId: 42 });
    expect(result.template.variableFields).toEqual({
      offer_id: "110566",
      stream: "src-3",
    });
  });

  it("11. telegramChatId, facebookAccountId, targetWebsiteName carry over", async () => {
    vi.mocked(getDb).mockResolvedValue(
      makeMockDb({
        source: [
          makeSourceRow({
            telegramChatId: "-1001735068614",
            facebookAccountId: 7,
            config: { targetWebsiteName: "Sotuvchi.com", targetTemplateType: "sotuvchi" },
          }),
        ],
      }),
    );
    const result = await userCaller(100).clone({ sourceId: 42 });
    expect(result.template.telegramChatId).toBe("-1001735068614");
    expect(result.template.facebookAccountId).toBe(7);
    expect(result.template.targetWebsiteName).toBe("Sotuvchi.com");
    expect(result.template.targetTemplateType).toBe("sotuvchi");
  });

  it("12. missing config (legacy rows with config=null) → empty variableFields, nulls passthrough", async () => {
    vi.mocked(getDb).mockResolvedValue(
      makeMockDb({
        source: [makeSourceRow({ config: undefined })],
      }),
    );
    const result = await userCaller(100).clone({ sourceId: 42 });
    // The router defaults variableFields to {}
    expect(result.template.variableFields).toEqual({});
  });
});

describe("integrationsRouter.clone — DB unavailable", () => {
  it("13. when DB is unavailable → INTERNAL_SERVER_ERROR", async () => {
    vi.mocked(getDb).mockResolvedValue(null as unknown as DbClient);
    await expect(userCaller(100).clone({ sourceId: 42 })).rejects.toMatchObject({
      code: "INTERNAL_SERVER_ERROR",
    });
  });
});
